# Generated by Django 2.1.3 on 2018-12-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chemSemSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=50)),
                ('syllabus', models.CharField(max_length=100)),
                ('imagelink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='phySemSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=50)),
                ('syllabus', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
